<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AzilEdu.Shared\AzilEdu.Shared.csproj" />
    <ProjectReference Include="..\AzilEdu.Api\AzilEdu.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\NewFolder\" />
  </ItemGroup>

</Project>
